## Exploring Dask Dashboard UI

In [3]:
from dask.distributed import Client
import dask.dataframe as df

client = Client(processes=False, threads_per_worker=2,
                n_workers=3, memory_limit='4GB')
client

### Data Taken from : https://www.kaggle.com/city-of-seattle/seattle-library-collection-inventory

In [6]:
data_path ="/Users/alexiuk/projects/data/kaggle/seattle-library/"
dummy_df = df.read_csv(data_path + 'broken_csvs/libary-part-0[0-2]*.csv')

In [7]:
dummy_df

Dask DataFrame Structure:
               Unnamed: 0 BibNum   Title  Author    ISBN PublicationYear Publisher Subjects ItemType ItemCollection FloatingItem ItemLocation ReportDate ItemCount
npartitions=30
                    int64  int64  string  string  string          string    string   string   string         string       string       string     string     int64
                      ...    ...     ...     ...     ...             ...       ...      ...      ...            ...          ...          ...        ...       ...
...                   ...    ...     ...     ...     ...             ...       ...      ...      ...            ...          ...          ...        ...       ...
                      ...    ...     ...     ...     ...             ...       ...      ...      ...            ...          ...          ...        ...       ...
                      ...    ...     ...     ...     ...             ...       ...      ...      ...            ...          ...          ...        ...       ...
Dask Name: to_pyarrow_string, 2 graph layers

In [8]:
dummy_df.describe().compute()

         Unnamed: 0        BibNum     ItemCount
count  5.854408e+06  5.854408e+06  5.854408e+06
mean   9.758064e+04  2.497912e+06  1.217808e+00
std    5.634743e+04  9.235110e+05  2.206553e+00
min    0.000000e+00  4.000000e+00  1.000000e+00
25%    4.948625e+04  2.348196e+06  1.000000e+00
50%    9.897250e+04  2.875306e+06  1.000000e+00
75%    1.484588e+05  3.148780e+06  1.000000e+00
max    1.979450e+05  3.343666e+06  7.920000e+02

In [9]:
dummy_df.head()

,Unnamed: 0,BibNum,Title,Author,ISBN,PublicationYear,Publisher,Subjects,ItemType,ItemCollection,FloatingItem,ItemLocation,ReportDate,ItemCount
0,0,3011076,A tale of two friends / adapted by Ellie O'Rya...,"O'Ryan, Ellie","1481425730, 1481425749, 9781481425735, 9781481...",2014.,"Simon Spotlight,","Musicians Fiction, Bullfighters Fiction, Best ...",jcbk,ncrdr,Floating,qna,2017-09-01T00:00:00.000,1
1,1,2248846,"Naruto. Vol. 1, Uzumaki Naruto / story and art...","Kishimoto, Masashi, 1974-",1569319006,"2003, c1999.","Viz,","Ninja Japan Comic books strips etc, Comic book...",acbk,nycomic,<NA>,lcy,2017-09-01T00:00:00.000,1
2,2,3209270,"Peace, love & Wi-Fi : a ZITS treasury / by Jer...","Scott, Jerry, 1955-","144945867X, 9781449458676",2014.,"Andrews McMeel Publishing,",Duncan Jeremy Fictitious character Comic books...,acbk,nycomic,<NA>,bea,2017-09-01T00:00:00.000,1
3,3,1907265,The Paris pilgrims : a novel / Clancy Carlile.,"Carlile, Clancy, 1930-",0786706155,c1999.,"Carroll & Graf,","Hemingway Ernest 1899 1961 Fiction, Biographic...",acbk,cafic,<NA>,cen,2017-09-01T00:00:00.000,1
4,4,1644616,"Erotic by nature : a celebration of life, of l...",<NA>,094020813X,"1991, c1988.","Red Alder Books/Down There Press,","Erotic literature American, American literatur...",acbk,canf,<NA>,cen,2017-09-01T00:00:00.000,1

In [10]:
# Currently in 1.2.1 inplace arguement is not supported
dummy_df = dummy_df.drop('Unnamed: 0', axis=1)

In [11]:
dummy_df.head()

,BibNum,Title,Author,ISBN,PublicationYear,Publisher,Subjects,ItemType,ItemCollection,FloatingItem,ItemLocation,ReportDate,ItemCount
0,3011076,A tale of two friends / adapted by Ellie O'Rya...,"O'Ryan, Ellie","1481425730, 1481425749, 9781481425735, 9781481...",2014.,"Simon Spotlight,","Musicians Fiction, Bullfighters Fiction, Best ...",jcbk,ncrdr,Floating,qna,2017-09-01T00:00:00.000,1
1,2248846,"Naruto. Vol. 1, Uzumaki Naruto / story and art...","Kishimoto, Masashi, 1974-",1569319006,"2003, c1999.","Viz,","Ninja Japan Comic books strips etc, Comic book...",acbk,nycomic,<NA>,lcy,2017-09-01T00:00:00.000,1
2,3209270,"Peace, love & Wi-Fi : a ZITS treasury / by Jer...","Scott, Jerry, 1955-","144945867X, 9781449458676",2014.,"Andrews McMeel Publishing,",Duncan Jeremy Fictitious character Comic books...,acbk,nycomic,<NA>,bea,2017-09-01T00:00:00.000,1
3,1907265,The Paris pilgrims : a novel / Clancy Carlile.,"Carlile, Clancy, 1930-",0786706155,c1999.,"Carroll & Graf,","Hemingway Ernest 1899 1961 Fiction, Biographic...",acbk,cafic,<NA>,cen,2017-09-01T00:00:00.000,1
4,1644616,"Erotic by nature : a celebration of life, of l...",<NA>,094020813X,"1991, c1988.","Red Alder Books/Down There Press,","Erotic literature American, American literatur...",acbk,canf,<NA>,cen,2017-09-01T00:00:00.000,1

In [12]:
group_publication_yr = dummy_df.groupby('PublicationYear').count()

In [13]:
group_publication_yr.compute()

2023-11-26 09:00:30,146 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 2.61 GiB -- Worker memory limit: 3.73 GiB

,BibNum,Title,Author,ISBN,Publisher,Subjects,ItemType,ItemCollection,FloatingItem,ItemLocation,ReportDate,ItemCount
PublicationYear,,,,,,,,,,,,
"""1972.",3,3,0,0,3,3,3,3,0,3,3,3
(1945).,6,6,6,0,6,6,6,6,0,6,6,6
(1945?).,6,6,6,0,6,6,6,6,0,6,6,6
(1966),23,23,23,0,23,23,23,23,0,23,23,23
(1967),23,23,23,0,23,18,23,23,0,23,23,23
...,...,...,...,...,...,...,...,...,...,...,...,...
©1921.,1,1,1,0,1,1,1,1,0,1,1,1
©1922.,1,1,1,0,1,1,1,1,0,1,1,1
©1995-2016.,1,1,0,0,1,1,1,1,0,1,1,1
"©2002, ℗1958.",1,1,1,0,1,1,1,1,1,1,1,1
"©2009, ©2006.",1,1,0,0,1,1,1,1,1,1,1,1

In [14]:
group_author = dummy_df.groupby('Author')['ItemCount'].sum()

In [15]:
group_author.compute()

2023-11-26 09:00:40,263 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 2.65 GiB -- Worker memory limit: 3.73 GiB

Author
!!! (Musical group)                            90
"Avion,", pseud.                                9
'N Sync (Musical group)                         8
(Alina Iosifovna)                               9
-Ky                                             4
                                               ..
Woolner, David B., 1955-                        1
Wright, Louis B. (Louis Booker), 1899-1984,     1
Yulinglaoren, active 18th century,,             1
Zabus, Vincent, 1971-                           2
ʾIyob ʾAbāta ʾEndāla,                           1
Name: ItemCount, Length: 239639, dtype: int64

In [16]:
len(dummy_df)

2023-11-26 09:00:50,383 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 2.73 GiB -- Worker memory limit: 3.73 GiB
2023-11-26 09:01:00,467 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 2.78 GiB -- Worker memory limit: 3.73 GiB

5854408

#### Reference : https://stackoverflow.com/a/29581287/8160718

In [17]:
import re
def extract_year(year_text, *args, **kwargs):
    if type(year_text)==type(''):
        return re.findall("[-+]?[\d]+(?:,\d\d\d)*[\.]?\d*(?:[eE][-+]?\d+)?", year_text)
    else:
        return year_text

seperate_publication_year = dummy_df['PublicationYear'].apply(extract_year,
                                                           axis=1,
                                                           meta=('PublicationYear', 'object'))

<>:4: SyntaxWarning: invalid escape sequence '\d'
<>:4: SyntaxWarning: invalid escape sequence '\d'
/var/folders/08/zn3bgg793fndlb4lnlcv_sxr0000gn/T/ipykernel_24413/1052063219.py:4: SyntaxWarning: invalid escape sequence '\d'
  return re.findall("[-+]?[\d]+(?:,\d\d\d)*[\.]?\d*(?:[eE][-+]?\d+)?", year_text)

In [18]:
seperate_publication_year.compute()

2023-11-26 09:01:10,492 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 2.72 GiB -- Worker memory limit: 3.73 GiB
2023-11-26 09:01:20,574 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 2.88 GiB -- Worker memory limit: 3.73 GiB

0                 ['2014.']
1         ['2003', '1999.']
2                 ['2014.']
3                 ['1999.']
4         ['1991', '1988.']
                ...
197623            ['1951.']
197624             ['1995']
197625             ['2006']
197626            ['2011.']
197627             ['2015']
Name: PublicationYear, Length: 5854408, dtype: string

In [19]:
dummy_df.nlargest(5, 'ItemCount').compute()

2023-11-26 09:01:30,617 - distributed.worker.memory - WARNING - Unmanaged memory use is high. This may indicate a memory leak or the memory may not be released to the OS; see https://distributed.dask.org/en/latest/worker-memory.html#memory-not-released-back-to-the-os for more information. -- Unmanaged memory: 2.77 GiB -- Worker memory limit: 3.73 GiB

,BibNum,Title,Author,ISBN,PublicationYear,Publisher,Subjects,ItemType,ItemCollection,FloatingItem,ItemLocation,ReportDate,ItemCount
122491,871761,Official gazette of the United States Patent a...,<NA>,<NA>,<NA>,"U.S. Dept. of Commerce, Patent and Trademark O...",Patents United States Periodicals,arbk,caref,<NA>,cen,2017-09-01T00:00:00.000,792
25811,871761,Official gazette of the United States Patent a...,<NA>,<NA>,<NA>,"U.S. Dept. of Commerce, Patent and Trademark O...",Patents United States Periodicals,arbk,caref,<NA>,cen,2017-10-01T00:00:00.000,792
56730,871761,Official gazette of the United States Patent a...,<NA>,<NA>,<NA>,"U.S. Dept. of Commerce, Patent and Trademark O...",Patents United States Periodicals,arbk,caref,<NA>,cen,2017-11-01T00:00:00.000,792
81986,871761,Official gazette of the United States Patent a...,<NA>,<NA>,<NA>,"U.S. Dept. of Commerce, Patent and Trademark O...",Patents United States Periodicals,arbk,caref,<NA>,cen,2017-12-01T00:00:00.000,792
8866,871761,Official gazette of the United States Patent a...,<NA>,<NA>,<NA>,"U.S. Dept. of Commerce, Patent and Trademark O...",Patents United States Periodicals,arbk,caref,<NA>,cen,2018-01-01T00:00:00.000,792

### Reference : https://distributed.readthedocs.io/en/latest/diagnosing-performance.html#